// Oefeningbibliotheek: voor élke oefening in het schema een demonstratie
// (pattern → components/figure.tsx), spiergroepen, techniek, fouten, ademhaling,
// tempo, rust en een tip van Meester Tiě Shān. Puur data — geen AI-calls.

export type Muscle =
  | 'schouders' | 'borst' | 'biceps' | 'triceps' | 'onderarmen' | 'buik' | 'obliques'
  | 'onderrug' | 'lats' | 'traps' | 'bilspieren' | 'quadriceps' | 'hamstrings'
  | 'kuiten' | 'scheenbeen' | 'adductoren' | 'heupbuigers'

export type Variant = { label: string; note: string; pattern?: string }
export type Exercise = {
  id: string
  naam: string
  pattern: string
  spieren: { p: Muscle[]; s: Muscle[] }
  techniek: string[]
  fouten: string[]
  adem: string
  tempo: string
  rust: string
  tip: string
  varianten?: Variant[]
  match: string[]
}

const E = (e: Exercise) => e

export const EXERCISES: Exercise[] = [
  // ———— PUSH ————
  E({ id: 'bench', naam: 'Bench press', pattern: 'bench', match: ['bench press'],
    spieren: { p: ['borst', 'triceps'], s: ['schouders'] },
    techniek: ['Schouderbladen samen en omlaag, borst hoog', 'Stang raakt onderkant borst, ellebogen ±45°', 'Voeten stevig in de vloer, lichte holling in de onderrug', 'Druk de stang licht schuin terug boven de schouders'],
    fouten: ['Ellebogen wijd uitflappen (schouderpijn)', 'Billen van de bank drukken', 'Stuiteren op de borst'],
    adem: 'Inademen bij zakken, krachtig uit bij het drukken.',
    tempo: '3s zakken · 1s pauze · krachtig omhoog', rust: '2-3 min',
    tip: 'Duw niet de stang weg — duw jezelf de bank in. De aarde geeft je kracht terug.',
    varianten: [{ label: 'Incline dumbbell', note: 'Bank op 30° — meer bovenkant borst, dumbbells zakken dieper dan een stang.', pattern: 'bench' }] }),
  E({ id: 'incdb', naam: 'Incline dumbbell press', pattern: 'bench', match: ['incline dumbbell'],
    spieren: { p: ['borst', 'schouders'], s: ['triceps'] },
    techniek: ['Bank 30-45°, dumbbells starten op borsthoogte', 'Onderarmen verticaal onder de gewichten', 'Druk licht naar elkaar toe bovenin'],
    fouten: ['Te zware dumbbells → schouders nemen over', 'Ellebogen te wijd'],
    adem: 'In bij zakken, uit bij drukken.', tempo: '3-1-1', rust: '90 s',
    tip: 'Laat de dumbbells zakken tot je een rek voelt over je borst — daar begint de groei.' }),
  E({ id: 'ohp', naam: 'Overhead press', pattern: 'ohp', match: ['overhead press', 'arnold press'],
    spieren: { p: ['schouders', 'triceps'], s: ['traps', 'buik'] },
    techniek: ['Stang op sleutelbeen, ellebogen iets vóór de stang', 'Bilspieren en buik keihard aanspannen', 'Druk de stang in één lijn omhoog, hoofd "door het raam"', 'Bovenin: schouders bij de oren, romp gestrekt'],
    fouten: ['Doorzakken in de onderrug (leunen)', 'Stang vóór het lichaam duwen i.p.v. erboven', 'Benen mee laten veren'],
    adem: 'Diep in vóór de rep, uit tijdens het drukken.',
    tempo: 'krachtig omhoog · 3s gecontroleerd terug', rust: '2-3 min',
    tip: 'Een berg drukt niet — hij rijst. Groei onder de stang uit, vanuit een ijzeren romp.',
    varianten: [{ label: 'Arnold press', note: 'Start met handpalmen naar je toe, draai uit tijdens het drukken — meer voorste schouderkop.', pattern: 'ohp' }] }),
  E({ id: 'dip', naam: 'Dips', pattern: 'dip', match: ['dip'],
    spieren: { p: ['borst', 'triceps'], s: ['schouders'] },
    techniek: ['Zak tot de bovenarm parallel aan de vloer', 'Licht voorover leunen voor borst-nadruk', 'Schouders laag — weg van je oren', 'Volledig strekken bovenin'],
    fouten: ['Te diep zakken met opgetrokken schouders', 'Halve reps bovenin', 'Slingeren met de benen'],
    adem: 'In bij zakken, uit bij drukken.', tempo: '2-3s zakken · krachtig op', rust: '2 min',
    tip: 'Je nulmeting is 19 — behandel elke rep als de eerste: volledig, beheerst, trots.',
    varianten: [{ label: 'Met gewicht', note: 'Riem met schijf zodra je 3×12 strak haalt.' }, { label: 'Bank-dips', note: 'Makkelijker: voeten op de vloer, handen op een bank.' }] }),
  E({ id: 'pushup', naam: 'Push-ups', pattern: 'pushup', match: ['push-up', 'pushup'],
    spieren: { p: ['borst', 'triceps'], s: ['schouders', 'buik'] },
    techniek: ['Eén rechte lijn van hiel tot kruin', 'Handen iets breder dan schouders, vingers naar voren', 'Ellebogen ±45° langs het lichaam', 'Borst raakt bijna de vloer — elke rep'],
    fouten: ['Heupen die zakken of pieken', 'Halve diepte bij vermoeidheid', 'Hoofd vooruit steken'],
    adem: 'In omlaag, krachtig uit omhoog.', tempo: '2-0-1, ritmisch', rust: '60-90 s',
    tip: 'In Dengfeng tel je ze niet meer — je wórdt ze. Bouw nu de standaard: geen enkele lelijke rep.',
    varianten: [{ label: 'Verhoogd (makkelijker)', note: 'Handen op een bank — zelfde vorm, minder last.' }, { label: 'Voeten verhoogd (zwaarder)', note: 'Voeten op een bank — meer schouder en bovenborst.' }] }),
  E({ id: 'lat', naam: 'Lateral raise', pattern: 'latraise', match: ['lateral raise'],
    spieren: { p: ['schouders'], s: ['traps'] },
    techniek: ['Lichte buiging in de ellebogen, vast', 'Til tot schouderhoogte, pink iets hoger dan duim', 'Beweeg vanuit de schouder, niet vanuit zwaai'],
    fouten: ['Te zwaar → rompzwaai', 'Boven schouderhoogte tillen', 'Schouders optrekken'],
    adem: 'Uit omhoog, in omlaag.', tempo: '1s op · 3s af', rust: '60 s',
    tip: 'Licht gewicht, volmaakte baan. Het ego tilt kilo\'s; de monnik tilt aandacht.' }),
  E({ id: 'tri', naam: 'Triceps pushdown', pattern: 'pushdown', match: ['pushdown', 'triceps extension', 'overhead triceps'],
    spieren: { p: ['triceps'], s: ['onderarmen'] },
    techniek: ['Ellebogen vast tegen de zij', 'Strek volledig, knijp 1 tel onderin', 'Alleen de onderarm beweegt'],
    fouten: ['Ellebogen laten wandelen', 'Met lichaamsgewicht duwen'],
    adem: 'Uit bij strekken, in terug.', tempo: '1-1-2', rust: '60 s',
    tip: 'De elleboog is je anker. Wat stil moet staan, houd je stil — dat ís de oefening.',
    varianten: [{ label: 'Overhead extension', note: 'Armen boven het hoofd — lange tricepskop krijgt de rek.', pattern: 'pushdown' }] }),
  E({ id: 'hspush', naam: 'Handstand-hold', pattern: 'handstand', match: ['handstand'],
    spieren: { p: ['schouders', 'triceps'], s: ['buik', 'onderarmen'] },
    techniek: ['Handen op schouderbreedte, vingers gespreid als wortels', 'Duw de vloer wég — schouders bij de oren', 'Ribben in, bilspieren aan: één rechte lijn', 'Blik tussen de handen'],
    fouten: ['Banaanrug (ribben uit)', 'Ellebogen die buigen', 'Te ver van de muur starten'],
    adem: 'Rustig blijven doorademen — nooit vasthouden.', tempo: 'houden, 15-45 s per set', rust: '90 s',
    tip: 'De wereld op zijn kop is ook maar een gezichtspunt. Adem, en de angst gaat liggen.' }),

  // ———— PULL ————
  E({ id: 'pullup', naam: 'Pull-ups', pattern: 'pullup', match: ['pull-up', 'pullup', 'pulldown', 'chin-up', 'chinup'],
    spieren: { p: ['lats', 'biceps'], s: ['onderarmen', 'buik', 'traps'] },
    techniek: ['Start vanuit een actieve hang: schouders laag', 'Trek de ellebogen naar je heupen', 'Kin over de stang zonder reiken', 'Volledig uithangen onderin — elke rep'],
    fouten: ['Kippen/slingeren', 'Halve reps (niet volledig strekken)', 'Schouders bij de oren laten hangen'],
    adem: 'Uit tijdens het trekken, in bij het zakken.', tempo: 'krachtig op · 3s af', rust: '2-3 min',
    tip: 'De negatieve helft bouwt de positieve. Wie beheerst zakt, leert stijgen.',
    varianten: [{ label: 'Chin-up', note: 'Handpalmen naar je toe — meer biceps, vaak 1-2 reps meer.' }, { label: 'Lat pulldown', note: 'Zelfde baan aan de machine — voor volume na je max-sets.' }, { label: 'Negatieven', note: 'Spring naar boven, zak in 5s — de snelste weg naar méér pull-ups.' }] }),
  E({ id: 'row', naam: 'Barbell row', pattern: 'row', match: ['row', 'pendlay'],
    spieren: { p: ['lats', 'traps'], s: ['biceps', 'onderrug', 'onderarmen'] },
    techniek: ['Scharnier tot de romp bijna parallel is', 'Rug lang en gespannen — geen bolling', 'Trek de stang naar je navel, ellebogen langs het lijf', 'Knijp de schouderbladen 1 tel samen'],
    fouten: ['Romp die elke rep meeveert', 'Trekken naar de borst met wijde ellebogen', 'Bolle onderrug'],
    adem: 'Uit bij trekken, in bij zakken.', tempo: '1-1-2', rust: '2 min',
    tip: 'De rug is je fundament voor elke worp en elke stand. Bouw hem als een tempelmuur: laag voor laag, recht.' }),
  E({ id: 'facepull', naam: 'Face pull', pattern: 'facepull', match: ['face pull'],
    spieren: { p: ['schouders', 'traps'], s: ['biceps'] },
    techniek: ['Kabel op ooghoogte, touw vast met duimen naar je toe', 'Trek naar je neus, ellebogen hoog en wijd', 'Eindig met de handen naast de oren — "spierbal-pose"'],
    fouten: ['Te zwaar → romp leunt achterover', 'Ellebogen zakken'],
    adem: 'Uit bij trekken.', tempo: '1-1-2', rust: '60 s',
    tip: 'Dit kleine werk beschermt je schouders voor het grote. Onderhoud is óók discipline.' }),
  E({ id: 'curl', naam: 'Biceps curl', pattern: 'curl', match: ['curl'],
    spieren: { p: ['biceps'], s: ['onderarmen'] },
    techniek: ['Ellebogen vast naast de romp', 'Draai de pols licht naar buiten tijdens het heffen', 'Volledig strekken onderin'],
    fouten: ['Zwaaien vanuit de heup', 'Halve strekking'],
    adem: 'Uit omhoog, in omlaag.', tempo: '1-1-3', rust: '60 s',
    tip: 'Traag omlaag is de helft van het werk — laat het gewicht nooit gewoon vallen.' }),
  E({ id: 'deadhang', naam: 'Dead hang', pattern: 'deadhang', match: ['dead hang', 'deadhang'],
    spieren: { p: ['onderarmen', 'lats'], s: ['schouders'] },
    techniek: ['Volledige greep — ook de pink werkt', 'Schouders actief: iets weg van de oren', 'Lichaam stil, benen ontspannen'],
    fouten: ['Volledig passief hangen (schouders in de oren)', 'Schommelen'],
    adem: 'Lang en laag ademen — het verlengt je hang.', tempo: 'houden tot vlak vóór falen', rust: '2 min',
    tip: 'Grip is wilskracht die je kunt meten. Je doel is 2 minuten — hang elke week iets langer.' }),
  E({ id: 'hlr', naam: 'Hangende beenheffing', pattern: 'hlr', match: ['beenheffing', 'leg raise'],
    spieren: { p: ['buik', 'heupbuigers'], s: ['onderarmen', 'obliques'] },
    techniek: ['Start in stille hang — geen zwaai', 'Kantel het bekken en til de benen gestrekt', 'Tenen richting stang; zak traag terug'],
    fouten: ['Slingeren voor momentum', 'Alleen knieën optrekken zonder bekkenkanteling'],
    adem: 'Uit bij heffen, in bij zakken.', tempo: '2s op · 3s af', rust: '90 s',
    tip: 'De stilte tussen de reps is de test. Wie niet slingert, is al sterk.' }),

  // ———— BENEN ————
  E({ id: 'squat', naam: 'Back squat', pattern: 'squat', match: ['back squat', 'squat ('],
    spieren: { p: ['quadriceps', 'bilspieren'], s: ['hamstrings', 'onderrug', 'buik'] },
    techniek: ['Stang op de achterste schouders, ellebogen onder de stang', 'Voeten schouderbreed, tenen licht uit', 'Zak tussen de knieën in — heup onder parallel als het kan', 'Knieën volgen de tenen, hielen blijven vol op de vloer'],
    fouten: ['Knieën die naar binnen vallen', 'Hielen los van de vloer (dorsiflexie! train je knee-to-wall)', 'Bolle onderrug in de diepte'],
    adem: 'Diep in bovenin, vastzetten, uit boven het zwaarste punt.',
    tempo: '3s zakken · geen stuiter · krachtig op', rust: '2-3 min',
    tip: 'Jouw rechterenkel bepaalt jouw diepte — forceer niets. Diepte verdien je centimeter voor centimeter.',
    varianten: [{ label: 'Leg press', note: 'Zelfde beweging aan de machine — veilig om zwaar te gaan zonder balansfactor.', pattern: 'legext' }, { label: 'Goblet squat', note: 'Dumbbell tegen de borst — perfect om diepte en houding te leren.' }] }),
  E({ id: 'legpress', naam: 'Leg press', pattern: 'legext', match: ['leg press'],
    spieren: { p: ['quadriceps', 'bilspieren'], s: ['hamstrings'] },
    techniek: ['Voeten midden op het platform, heupbreed', 'Zak tot 90° of zo diep als de onderrug plat blijft', 'Druk door de hele voet, niet alleen de tenen'],
    fouten: ['Onderrug die van het kussen krult', 'Knieën op slot rammen bovenin'],
    adem: 'In bij zakken, uit bij drukken.', tempo: '3-0-1', rust: '2 min',
    tip: 'De machine draagt de balans, jij draagt de eerlijkheid: volle diepte, elke rep.' }),
  E({ id: 'splitsq', naam: 'Split squat', pattern: 'splitsquat', match: ['split squat', 'bulgarian'],
    spieren: { p: ['quadriceps', 'bilspieren'], s: ['adductoren', 'buik'] },
    techniek: ['Grote stap: voorvoet ver genoeg dat de knie boven de enkel blijft', 'Zak recht omlaag — achterknie richting vloer', 'Romp licht voorover voor bil-nadruk', 'Start met je rechterbeen (geblesseerde kant) — die zet de standaard'],
    fouten: ['Te korte stap (knie ver voorbij tenen)', 'Duwen vanaf het achterbeen', 'Wankelen door te smalle stand'],
    adem: 'In omlaag, uit omhoog.', tempo: '2-1-1', rust: '90 s per been',
    tip: 'Eén been tegelijk liegt nooit. Wat rechts kan, is jouw echte kracht — links volgt de zwakste.',
    varianten: [{ label: 'Bulgarian split squat', note: 'Achtervoet op een bank — meer last op het voorbeen, meer rek in de heupbuiger.' }] }),
  E({ id: 'legext', naam: 'Leg extension', pattern: 'legext', match: ['leg extension'],
    spieren: { p: ['quadriceps'], s: [] },
    techniek: ['Knie-as gelijk aan machine-as', 'Strek volledig en knijp 1 tel', 'Zak traag — niet laten vallen'],
    fouten: ['Zwiepen met licht gewicht', 'Heup die van het kussen komt'],
    adem: 'Uit bij strekken.', tempo: '1-1-3', rust: '60-90 s',
    tip: 'Sterke quads vangen elke landing die je enkel nog niet kan. Dit is bescherming, geen ijdelheid.' }),
  E({ id: 'rdl', naam: 'Romanian deadlift', pattern: 'hinge', match: ['romanian', 'rdl'],
    spieren: { p: ['hamstrings', 'bilspieren'], s: ['onderrug', 'onderarmen'] },
    techniek: ['Heupen naar achteren — de stang glijdt langs de benen', 'Knieën licht gebogen, vast', 'Rug lang; zak tot de rek in de hamstrings', 'Heupen naar voren knijpen bovenin — niet leunen'],
    fouten: ['Buigen vanuit de rug in plaats van de heup', 'Stang ver van het lichaam', 'Te diep zakken zonder hamstringlengte'],
    adem: 'In bovenaan, uit bij het omhoog komen.',
    tempo: '3s af · 1s rek · krachtig op', rust: '2-3 min',
    tip: 'Het scharnier is de moeder van alle kracht — elke worp en elke sprong begint in je heup.' }),
  E({ id: 'hamcurl', naam: 'Hamstring curl', pattern: 'hamcurl', match: ['hamstring curl', 'nordic'],
    spieren: { p: ['hamstrings'], s: ['kuiten'] },
    techniek: ['Heupen blijven in het kussen gedrukt', 'Hiel naar de bil in een rustige boog', 'Traag terug tot bijna gestrekt'],
    fouten: ['Heupen die opkomen', 'Gewicht laten terugvallen'],
    adem: 'Uit bij buigen.', tempo: '1-1-3', rust: '90 s',
    tip: 'Sterke hamstrings zijn de stille wachters van je knie én je enkel.',
    varianten: [{ label: 'Nordic curl', note: 'Knielend, partner/bank houdt je enkels: zak zo traag mogelijk voorover — brutaal effectief.' }] }),
  E({ id: 'hipthrust', naam: 'Hip thrust', pattern: 'brug', match: ['hip thrust'],
    spieren: { p: ['bilspieren'], s: ['hamstrings', 'quadriceps'] },
    techniek: ['Schouderbladen op de bank, voeten onder de knieën', 'Duw door de hielen, kin licht in', 'Bovenin: romp horizontaal, billen 1-2 tellen keihard knijpen'],
    fouten: ['Overstrekken van de onderrug bovenin', 'Te ver van je billen geplaatste voeten'],
    adem: 'Uit omhoog, in omlaag.', tempo: '1-2-2', rust: '2 min',
    tip: 'Glute max is je motor voor sprint en sprong. Kracht hier = minder vraag aan je enkel.' }),

  // ———— ENKEL-REHA ————
  E({ id: 'kneetowall', naam: 'Knee-to-wall mobilisatie', pattern: 'ktw', match: ['knee-to-wall'],
    spieren: { p: ['kuiten'], s: ['scheenbeen'] },
    techniek: ['Voet recht naar voren, hiel blijft vól op de vloer', 'Duw de knie over de kleine teen richting muur', 'Zoek de rand — pijnvrij, wel stevige rek', 'Meet wekelijks je afstand (dit is een fasecriterium!)'],
    fouten: ['Hiel die stiekem lost', 'Voet naar buiten draaien om te smokkelen', 'Doorduwen in scherpe pijn'],
    adem: 'Rustig door — 2s per rock.', tempo: '3×10 rocks per kant', rust: '30 s',
    tip: 'Rechts staat op 2 cm, links op 6. Dit is je belangrijkste centimeterwerk — elke dag, geduldig als water op steen.' }),
  E({ id: 'calf', naam: 'Kuit heffen (dubbelbenig)', pattern: 'calfraise', match: ['kuit heffen dubbelbenig', 'kuit heffen'],
    spieren: { p: ['kuiten'], s: [] },
    techniek: ['Volledig omhoog op de bal van de voet — 3s op, 3s neer', 'Groot bereik: van lichte rek tot volle teenstand', 'Gelijk gewicht op beide voeten (kijk je rechterkant niet uit de wind)'],
    fouten: ['Kort veren in het midden van het bereik', 'Gewicht ongemerkt naar links verplaatsen'],
    adem: 'Uit omhoog, in omlaag.', tempo: '3-1-3, traag', rust: '60 s',
    tip: 'Van 3 naar 25 herhalingen — dit is je poort naar elke sprong in Dengfeng. Traag bouwt de pees.',
    varianten: [{ label: 'Eenbenig + gewicht (fase 2)', note: 'Op één been met dumbbell — jaag symmetrie na: rechts verdient dezelfde standaard als links.' }, { label: 'Zittend (soleus)', note: 'Knie op 90° — de diepe kuitspier die je bij elke landing draagt.' }, { label: 'Excentrische hieldaling', note: 'Met twee benen op, met één traag (5s) neer van een opstapje.' }] }),
  E({ id: 'tib', naam: 'Tibialis raises', pattern: 'tibialis', match: ['tibialis'],
    spieren: { p: ['scheenbeen'], s: [] },
    techniek: ['Rug tegen de muur, hielen ±30 cm ervoor', 'Trek de tenen zo hoog mogelijk op', 'Traag terug — raak de vloer nauwelijks'],
    fouten: ['Te dicht bij de muur staan (te makkelijk)', 'Snel klappen zonder controle'],
    adem: 'Rustig ritme.', tempo: '2-1-2', rust: '45 s',
    tip: 'De vergeten spier die je voet optilt bij elke stap bergop. Shaolin kent geen vergeten spieren.' }),
  E({ id: 'band', naam: 'Elastiek: enkel alle richtingen', pattern: 'bandenkel', match: ['elastiek'],
    spieren: { p: ['kuiten', 'scheenbeen'], s: [] },
    techniek: ['Zit met gestrekt been, band om de voorvoet', 'Werk in 4 richtingen: op, neer, in, uit', 'Beweeg alléén de enkel — het been ligt stil', 'Traag en met volle spanning, ook terug'],
    fouten: ['Bewegen vanuit de knie of heup', 'Band laten terugschieten'],
    adem: 'Rustig door.', tempo: '2-0-2 per richting', rust: '30 s',
    tip: 'Klein werk, groot fundament. De banden rond je enkel leren hier weer luisteren.' }),
  E({ id: 'balance', naam: 'Eenbenige balans', pattern: 'balance', match: ['balans'],
    spieren: { p: ['kuiten', 'scheenbeen'], s: ['bilspieren', 'buik'] },
    techniek: ['Sta op één been, lichte knik in de knie', 'Grote teen actief in de vloer gedrukt', 'Ogen dicht zodra 30s met open lukt', 'Foam/kussen eronder voor de volgende stap'],
    fouten: ['Doorgezakte heup (bekken scheef)', 'Star vastgrijpen met de tenen'],
    adem: 'Laag en rustig — adem is balans.', tempo: '3×30-45 s per kant', rust: '30 s',
    tip: 'Balans is geen stilstand maar duizend micro-correcties. Verwelkom het wiebelen — dát is de training.' }),
  E({ id: 'stepdown', naam: 'Step-down', pattern: 'stepdown', match: ['step-down'],
    spieren: { p: ['quadriceps', 'bilspieren'], s: ['kuiten'] },
    techniek: ['Sta op een opstapje, zak gecontroleerd tot de vrije hiel tikt', 'Knie blijft boven de voet — niet naar binnen', 'Duw terug omhoog zonder afzet van het vrije been'],
    fouten: ['Vallen in plaats van zakken', 'Knie die naar binnen duikt (kijk in een spiegel)'],
    adem: 'In omlaag, uit omhoog.', tempo: '3s zakken', rust: '60 s',
    tip: 'Dit is de landing van een sprong, vertraagd tot een les. Beheers hem traag, verdien hem snel.' }),
  E({ id: 'yreach', naam: 'Y-balance / star reach', pattern: 'balance', match: ['y-balance', 'star reach'],
    spieren: { p: ['bilspieren', 'kuiten'], s: ['quadriceps'] },
    techniek: ['Sta op één been, reik met de andere zo ver mogelijk in 3 richtingen', 'Standbeen-knie boven de voet', 'Reik langzaam — de afstand is het cijfer, de controle de winst'],
    fouten: ['Hakken van het standbeen los', 'Snelheid verwarren met bereik'],
    adem: 'Rustig door.', tempo: '3×5 per richting', rust: '45 s',
    tip: 'Reik met je voet, maar meet met je enkel: <4 cm verschil per richting is je fase-2-doel.' }),
  E({ id: 'pogo', naam: 'Pogo-hops (laag)', pattern: 'hop', match: ['pogo'],
    spieren: { p: ['kuiten'], s: ['quadriceps'] },
    techniek: ['Lage, verende sprongetjes op de bal van de voet', 'Stijve enkel: land en kaats als een veer', 'Hielen raken de vloer nauwelijks', 'ALLEEN pijnvrij — dit is je eerste impact'],
    fouten: ['Te hoog willen springen', 'Zakken door de enkel bij landing (plof)'],
    adem: 'Ritmisch, ontspannen.', tempo: '3×20, licht en snel', rust: '60 s',
    tip: 'De eerste sprongetjes na je blessure — klein als regendruppels. De 24-uursregel beslist of ze mochten.' }),
  E({ id: 'hopsingle', naam: 'Single hop for distance', pattern: 'hop', match: ['single hop', 'triple hop', 'bounding'],
    spieren: { p: ['kuiten', 'quadriceps', 'bilspieren'], s: ['hamstrings'] },
    techniek: ['Spring van één been, land op hetzélfde been', 'Landing houden: 2s stil staan, dan pas tellen', 'Meet links én rechts — symmetrie ≥90% is het criterium', 'Zachte knie en heup vangen, niet de enkel alleen'],
    fouten: ['Landing niet "plakken" (bijstappen)', 'Alleen afstand jagen, vorm vergeten'],
    adem: 'Uit bij afzet.', tempo: '4×5 per kant, volledig herstel', rust: '90 s',
    tip: 'De sprong liegt niet en de landing vergeeft niet. Plak elke landing — dát is je go/no-go.' }),
  E({ id: 'sidehop', naam: 'Side hops', pattern: 'hop', match: ['side hop', 'zijwaartse hop'],
    spieren: { p: ['kuiten'], s: ['adductoren', 'bilspieren'] },
    techniek: ['Spring zijwaarts over een lijn heen en weer (±30 cm)', 'Blijf op de bal van de voet, verend', 'Tel het aantal in 30s — beide kanten'],
    fouten: ['Te wijd springen (traag)', 'Inzakken op de landing'],
    adem: 'Ritmisch.', tempo: '3×20-30 s per kant', rust: '60 s',
    tip: 'Zijwaarts is de richting waarin je enkel viel — en dus de richting waarin hij het sterkst moet worden.' }),
  E({ id: 'boxjump', naam: 'Box jumps', pattern: 'boxjump', match: ['box jump', 'depth jump', 'reactieve sprongen'],
    spieren: { p: ['quadriceps', 'bilspieren', 'kuiten'], s: ['hamstrings'] },
    techniek: ['Kwartsquat → armen zwaaien → explosief', 'Land zácht midden op de box, knieën uit', 'Stap af (niet terugspringen) zolang je in fase 3 zit'],
    fouten: ['Te hoge box (landing in diepe hurk)', 'Terugspringen van de box', 'Knieën naar binnen bij landing'],
    adem: 'Uit bij afzet.', tempo: '4×5, vers en explosief', rust: '90 s',
    tip: 'Spring niet óp de doos — spring door de vloer heen. De doos vangt slechts wat de aarde je gaf.' }),
  E({ id: 'landing', naam: 'Afrem- & landingsdrills', pattern: 'boxjump', match: ['landingsdrill', 'afrem'],
    spieren: { p: ['quadriceps', 'bilspieren'], s: ['kuiten', 'hamstrings'] },
    techniek: ['Val van een lage verhoging, land in atletische stand', 'Stil als een standbeeld: 2s vasthouden', 'Heup vangt, knieën sporen, romp stil'],
    fouten: ['Doorveren tot de hielen klappen', 'Kijken naar de voeten'],
    adem: 'Uit bij landing.', tempo: '3×6, kwaliteit boven alles', rust: '60 s',
    tip: 'Wie kan stoppen, mag versnellen. Remmen is de vergeten helft van snelheid.' }),
  E({ id: 'agility', naam: 'Agility: figure-8 & carioca', pattern: 'run', match: ['agility', 'carioca', 'figure-8'],
    spieren: { p: ['kuiten', 'quadriceps'], s: ['adductoren', 'bilspieren'] },
    techniek: ['Begin ruim en traag, verklein de bochten per ronde', 'Blijf laag in de heupen', 'Let op je enkel bij elke richtingswissel — geen klappen'],
    fouten: ['Te snel te scherp willen draaien', 'Rechtop komen in de bocht'],
    adem: 'Ritmisch.', tempo: '4 rondes, opbouwend', rust: '90 s',
    tip: 'De bocht test wat de rechte lijn verbergt. Eert je enkel de bocht, dan is hij bijna thuis.' }),
  E({ id: 'kicks', naam: 'Trappen op pads', pattern: 'kick', match: ['trapvolume', 'trap-hoogte', 'shadow-kicks', 'front kick'],
    spieren: { p: ['heupbuigers', 'quadriceps'], s: ['bilspieren', 'buik', 'kuiten'] },
    techniek: ['Knie eerst hoog optrekken (chamber), dan pas strekken', 'Standbeen draait mee, hiel licht', 'Trek de trap even snel terug als hij ging', 'Hoogte komt uit de heup, niet uit leunen'],
    fouten: ['Trap "zwaaien" zonder chamber', 'Achterover hangen voor hoogte', 'Standvoet plat vast (knie-torsie!)'],
    adem: 'Korte krachtige uitademing per trap.', tempo: '5×10 per kant, gecontroleerd', rust: '60 s',
    tip: '一步一步 — eerst de knie, dan de voet. Tienduizend keer de chamber, en de hoogte komt vanzelf.' }),

  // ———— STANCES ————
  E({ id: 'mabu', naam: 'Ma Bu (paardstand)', pattern: 'mabu', match: ['ma bu', 'paardstand'],
    spieren: { p: ['quadriceps', 'bilspieren'], s: ['adductoren', 'buik'] },
    techniek: ['Voeten ±2 schouderbreedtes, tenen vooruit', 'Zak tot de dijen richting parallel — rug kaarsrecht', 'Knieën naar buiten geduwd, boven de voeten', 'Handen als vuisten aan de heup of gestrekt vooruit'],
    fouten: ['Billen naar achteren steken (het is geen squat)', 'Knieën die naar binnen zakken', 'Schouders die optrekken bij vermoeidheid'],
    adem: 'Laag in de buik, lang en stil — de adem draagt de stand.',
    tempo: 'houden — jouw schema bouwt van 30s naar 2,5+ min', rust: '60-90 s',
    tip: 'Ma Bu is de eerste poort van Shaolin. Als je benen branden, begint de training pas — zak een vingerbreedte dieper.' }),
  E({ id: 'gongbu', naam: 'Gong Bu (booghouding)', pattern: 'gongbu', match: ['gong bu', 'booghouding'],
    spieren: { p: ['quadriceps', 'bilspieren'], s: ['heupbuigers', 'kuiten'] },
    techniek: ['Lange stand: voorknie boven de enkel, achterbeen gestrekt', 'Achtervoet ±45° in, vol op de vloer', 'Heupen recht naar voren, romp verticaal'],
    fouten: ['Achterhiel die lost', 'Heupen die opendraaien'],
    adem: 'Rustig en diep.', tempo: '3×30 s per kant', rust: '45 s',
    tip: 'De boog spant kracht tussen beide benen. Voel de lijn van achterhiel tot kruin — dat is de pijl.' }),
  E({ id: 'xubu', naam: 'Xu Bu (lege stand)', pattern: 'xubu', match: ['xu bu', 'lege stand'],
    spieren: { p: ['quadriceps'], s: ['kuiten', 'buik'] },
    techniek: ['90% gewicht op het achterbeen, diep gezakt', 'Voorvoet raakt de vloer slechts met de tenen — "leeg"', 'Romp rechtop, klaar om te trappen'],
    fouten: ['Gewicht stiekem op het voorbeen', 'Niet diep genoeg zakken'],
    adem: 'Stil en laag.', tempo: '3×20 s per kant', rust: '45 s',
    tip: 'Het lege been kan trappen omdat het niets draagt. Leegte is hier geen zwakte maar potentie.' }),
  E({ id: 'wallsit', naam: 'Wall sit', pattern: 'wallsit', match: ['wall sit'],
    spieren: { p: ['quadriceps'], s: ['bilspieren'] },
    techniek: ['Rug vlak tegen de muur, knieën op 90°', 'Knieën boven de enkels, handen los van de benen', 'Gewicht door de hielen'],
    fouten: ['Handen op de dijen steunen', 'Wegzakken onder de 90°'],
    adem: 'Rustig blijven ademen — niet klemmen.', tempo: 'houden tot RPE 9', rust: '90 s',
    tip: 'Nulmeting 85s, doel 3 minuten. De muur oordeelt niet — hij wacht alleen.' }),

  // ———— MOBILITEIT ————
  E({ id: 'frontsplit', naam: 'Front split-progressie', pattern: 'frontsplit', match: ['front split', 'spagaat'],
    spieren: { p: ['hamstrings', 'heupbuigers'], s: ['adductoren'] },
    techniek: ['Voorbeen gestrekt, achterknie eerst op de vloer', 'Heupen recht naar voren houden (vierkant)', 'Zak per ademcyclus een fractie — nooit stuiteren', 'PNF: 30s rek → 6s aanspannen tegen de vloer → dieper'],
    fouten: ['Heup opendraaien om diepte te faken', 'Stuiteren', 'Vergeten te ademen'],
    adem: 'Elke uitademing = een millimeter dieper.', tempo: '4 PNF-cycli per kant', rust: '30 s',
    tip: 'De spagaat is een onderhandeling van maanden, geen gevecht van vandaag. Meet elke 4 weken — het Kompas kijkt mee.' }),
  E({ id: 'straddle', naam: 'Straddle / side split', pattern: 'butterfly', match: ['straddle', 'side split'],
    spieren: { p: ['adductoren'], s: ['hamstrings'] },
    techniek: ['Benen wijd, tenen en knieën naar het plafond', 'Kantel vanuit het bekken naar voren, rug lang', 'Steun op de handen en wandel millimeters vooruit'],
    fouten: ['Knieën die naar voren rollen', 'Bolle rug naar de vloer duwen'],
    adem: 'Lang uit bij elke verdieping.', tempo: '4×40 s of PNF', rust: '30 s',
    tip: 'Zijwaartse ruimte opent de zijwaartse trap. De heup geeft zich alleen aan wie dagelijks terugkomt.' }),
  E({ id: 'couch', naam: 'Couch stretch (heupbuigers)', pattern: 'couch', match: ['couch', 'heupbuiger'],
    spieren: { p: ['heupbuigers', 'quadriceps'], s: [] },
    techniek: ['Achterknie op de vloer, scheen tegen muur/bank omhoog', 'Bekken achterover kantelen — dáár zit de rek', 'Romp rechtop brengen voor meer diepte'],
    fouten: ['Hol trekken van de onderrug', 'Hangen zonder bekkenkanteling'],
    adem: 'Diep en laag.', tempo: '3×40 s per kant', rust: '30 s',
    tip: 'Zittende uren maken korte heupen; korte heupen stelen je traphoogte. Hier win je die terug.' }),
  E({ id: 'hamstretch', naam: 'Hamstrings PNF', pattern: 'hamstring', match: ['hamstrings pnf', 'hamstring'],
    spieren: { p: ['hamstrings'], s: ['kuiten'] },
    techniek: ['Rug lang — scharnier vanuit de heup', 'PNF: 30s rek → 6s been in de vloer/band drukken → dieper', 'Voet gebogen (flex) pakt ook de kuit mee'],
    fouten: ['Bolle rug om verder te komen', 'Verend trekken'],
    adem: 'Uit bij elke verdieping.', tempo: '3-4 PNF-cycli per kant', rust: '30 s',
    tip: 'Lange hamstrings = hoge front kick + veilige heupscharnier. Twee vliegen, één geduldige klap.' }),
  E({ id: 'squathold', naam: 'Diepe squat hold', pattern: 'squathold', match: ['squat hold', 'diepe squat'],
    spieren: { p: ['adductoren', 'quadriceps'], s: ['kuiten', 'onderrug'] },
    techniek: ['Hielen plat, zo diep als je enkel toelaat', 'Ellebogen duwen de knieën zacht naar buiten', 'Rug lang, borst open — dit is een rusthouding, geen kramp'],
    fouten: ['Hielen die zweven (pak steun of til de hielen op een schijf)', 'Hangen in de knieën i.p.v. actief zitten'],
    adem: 'Traag; elke uitademing zakt je dieper.', tempo: 'verzamel 1-2+ min totaal', rust: 'n.v.t.',
    tip: 'In China is dit zitten. Maak van de diepe hurk je thuis en Dengfeng voelt als thuiskomen.' }),
  E({ id: 'n9090', naam: '90/90 heuprotaties', pattern: 'butterfly', match: ['90/90'],
    spieren: { p: ['bilspieren', 'adductoren'], s: ['heupbuigers'] },
    techniek: ['Beide knieën op 90°: één been voor, één opzij', 'Kantel het bekken voorover over het voorbeen', 'Wissel vloeiend van kant zonder handen (gevorderd)'],
    fouten: ['Bol wegzakken in de rug', 'Te snel wisselen'],
    adem: 'Rustig door.', tempo: '3×8 per kant', rust: '30 s',
    tip: 'De heup draait in kommen, niet in lijnen. Smeer beide kommen, elke dag.' }),
  E({ id: 'dislocate', naam: 'Schouder-dislocates', pattern: 'dislocate', match: ['dislocates', 'thoracale'],
    spieren: { p: ['schouders'], s: ['borst', 'traps'] },
    techniek: ['Stok/band breed vast, armen gestrekt', 'In één boog van heup → boven het hoofd → achter je', 'Verklein de greep alleen als het pijnvrij blijft'],
    fouten: ['Ellebogen buigen onderweg', 'Te smalle greep te vroeg'],
    adem: 'Rustig, vloeiend.', tempo: '2×10, traag', rust: '30 s',
    tip: 'Open schouders dragen de staf, de handstand én je houding. Ruimte eerst, kracht volgt.' }),

  // ———— CONDITIE ————
  E({ id: 'zone2', naam: 'Zone 2 — fiets/roeier', pattern: 'bike', match: ['zone 2', 'fiets'],
    spieren: { p: ['quadriceps'], s: ['kuiten', 'hamstrings'] },
    techniek: ['Tempo waarop je nog een gesprek kunt voeren', 'Cadans 80-95 rpm, licht verzet', 'Blijf lang op het zadel — de motor bouwt in stilte'],
    fouten: ['Te hard gaan (zone 3 is géén zone 2)', 'Sessies inkorten omdat het "te makkelijk" voelt'],
    adem: 'Neusademhaling als graadmeter: lukt dat niet, dan te snel.', tempo: 'rustig en constant', rust: 'n.v.t.',
    tip: 'De trage motor draagt straks de 6 uur per dag. Saai is hier een compliment.',
    varianten: [{ label: 'Roeier', note: 'Zelfde zone, meer rug — wissel gerust af.', pattern: 'rower' }] }),
  E({ id: 'interval', naam: 'Intervallen fiets/roeier', pattern: 'rower', match: ['intervallen'],
    spieren: { p: ['quadriceps', 'lats'], s: ['hamstrings', 'kuiten'] },
    techniek: ['Roeier: benen → romp → armen, terug in omgekeerde volgorde', '2 min hard = zwaar maar herhaalbaar', 'Herstelminuut echt rustig — durf te zakken'],
    fouten: ['Eerste interval sprinten, laatste kruipen', 'Alleen armen trekken op de roeier'],
    adem: 'Krachtig ritme; koppel adem aan de slag.', tempo: '6×2 min hard / 1 min rust', rust: 'in het blok',
    tip: 'Verdeel je vuur: de zesde ronde hoort even sterk te zijn als de eerste. Dát is meesterschap.' }),
  E({ id: 'jog', naam: 'Wandel-jog opbouw', pattern: 'run', match: ['wandel-jog', 'joggen', 'tempoloop', '400 m', '5 km', 'hardlopen'],
    spieren: { p: ['quadriceps', 'kuiten'], s: ['hamstrings', 'bilspieren'] },
    techniek: ['Korte, lichte passen — land onder je lichaam', 'Cadans hoog (±170+), voetplant zacht', 'Vlakke ondergrond; stop bij enkelpijn >2', 'De dag erna groen? Dan mag de volgende stap'],
    fouten: ['Te grote passen (hiellandingen ver voor je)', 'Door pijn heen lopen — de 24-uursregel is wet'],
    adem: 'Praattempo; neus in, mond uit.', tempo: 'volgens je faseschema', rust: 'wandelminuten',
    tip: 'Je eerste meters hardlopen sinds de blessure. Loop zacht als mist — de berg beloont geduld met kilometers.' }),
  E({ id: 'circuit', naam: 'Martial conditioning circuit', pattern: 'kick', match: ['martial conditioning', 'burpees', 'touwtje'],
    spieren: { p: ['quadriceps', 'borst', 'buik'], s: ['schouders', 'kuiten'] },
    techniek: ['Burpees: borst raakt de vloer, sprong met open heupen', 'Touwtje: laag en verend op de bal van de voet', 'Shadow-kicks: chamber eerst, techniek boven tempo', 'Rond elke ronde af vóór je opnieuw begint'],
    fouten: ['Vorm laten smelten in ronde 3', 'Pauzes laten uitdijen'],
    adem: 'Uit op elke inspanning; herstel actief.', tempo: '5 rondes, klok mee', rust: '60-90 s per ronde',
    tip: 'Dit is een dag Dengfeng in het klein: techniek als je moe bent is de enige techniek die telt.' }),

  // ———— CORE & GEEST ————
  E({ id: 'plank', naam: 'Plank', pattern: 'plank', match: ['plank'],
    spieren: { p: ['buik'], s: ['schouders', 'bilspieren', 'onderrug'] },
    techniek: ['Ellebogen onder de schouders', 'Bekken achterover gekanteld: ribben in, billen aan', 'Duw de vloer weg — geen hangende borst', 'Eén lijn, van hiel tot kruin'],
    fouten: ['Zakkende heupen (holle rug)', 'Piekende billen', 'Adem vasthouden'],
    adem: 'Blijven ademen, laag en rustig.', tempo: 'houden tot vorm breekt — dan stoppen', rust: '60-90 s',
    tip: 'Het is geen wedstrijd tegen de klok maar tegen de eerste millimeter verval. Breekt de lijn, dan is de set klaar.',
    varianten: [{ label: 'Ab-wheel / hollow', note: 'Zelfde ribben-in-spanning, bewegend: rol uit zover je de lijn houdt.' }] }),
  E({ id: 'pallof', naam: 'Pallof press', pattern: 'pallof', match: ['pallof'],
    spieren: { p: ['obliques', 'buik'], s: ['schouders'] },
    techniek: ['Kabel/band zijwaarts op borsthoogte', 'Druk de handen recht vooruit — laat de band je níét draaien', '2s uitgestrekt houden, gecontroleerd terug'],
    fouten: ['Meedraaien met de trek', 'Te ver van het anker (geen spanning)'],
    adem: 'Uit bij uitdrukken.', tempo: '2-2-2', rust: '60 s',
    tip: 'Kracht die niet beweegt is óók kracht. Je taille leert hier nee zeggen — elke worp dankt haar straks.' }),
  E({ id: 'meditatie', naam: 'Zitmeditatie', pattern: 'meditatie', match: ['zitmeditatie', 'meditatie'],
    spieren: { p: [], s: [] },
    techniek: ['Zit op de voorste helft van een kussen, knieën lager dan heupen', 'Rug rijst op uit het bekken — kruin naar het plafond', 'Ogen zacht dicht of halfopen naar de vloer', 'Tel ademhalingen 1-10, begin opnieuw bij afdwalen'],
    fouten: ['Vechten tegen gedachten (laat ze passeren als wolken)', 'Ingezakte onderrug'],
    adem: 'Laag in de buik; uitademing langer dan inademing.', tempo: 'volgens schema (10→20 min)', rust: 'n.v.t.',
    tip: 'De geest is een aap; geef hem één taak — de adem — en hij wordt een os. Chan begint waar tellen eindigt.' }),
  E({ id: 'boxadem', naam: 'Box-ademhaling', pattern: 'meditatie', match: ['box-ademhaling', 'ademwerk'],
    spieren: { p: [], s: [] },
    techniek: ['4 tellen in — 4 vast — 4 uit — 4 vast', 'Adem laag: de buik beweegt, de schouders niet', 'Gebruik de timer in de app (Vandaag → Ademwerk)'],
    fouten: ['Hoog in de borst ademen', 'Forceren van het ritme'],
    adem: 'Dit ís de oefening.', tempo: '3+ min', rust: 'n.v.t.',
    tip: 'Vier gelijke zijden — adem als een tempelmuur. Gebruik hem vóór zware sets en ná zware dagen.' }),
  E({ id: 'walk', naam: 'Rustige wandeling', pattern: 'run', match: ['wandeling', 'wandelen'],
    spieren: { p: ['kuiten'], s: ['quadriceps'] },
    techniek: ['Stevig doorstappen, armen los mee', 'Let op je enkel: geen compensatie-pas', 'Buiten > binnen: licht en lucht zijn ook herstel'],
    fouten: ['Slenteren en het "training" noemen', 'Doorlopen bij opkomende enkelpijn'],
    adem: 'Neus, rustig.', tempo: '20-45 min', rust: 'n.v.t.',
    tip: '45 minuten pijnvrij stevig wandelen is een fase-criterium. Elke wandeling is stille vooruitgang.' }),
]

// Vind de bibliotheek-entry bij een oefeningnaam uit het schema (fuzzy, NL).
export function findExercise(name: string): Exercise | null {
  const n = name.toLowerCase()
  let best: Exercise | null = null
  let bestLen = 0
  for (const ex of EXERCISES) {
    for (const m of ex.match) {
      if (n.includes(m) && m.length > bestLen) { best = ex; bestLen = m.length }
    }
  }
  return best
}
